### ISSUE TITLE
do i have to install Chromium instead of chrome to run the test?

### ISSUE THREAD

**Issue by bingowrt** [aimkiray/auto-metamask#2]
Traceback (most recent call last):
  File "/Users/runtaowang/Documents/pyprojects/selenium/aa.py", line 14, in <module>
    driver = setupWebdriver(metamask_path, '/Applications/Chromium.app/Contents/MacOS/Chromium')
  File "/Users/runtaowang/opt/anaconda3/lib/python3.9/site-packages/auto_metamask/core.py", line 69, in setupWebdriver
    s = Service(ChromeDriverManager(chrome_type=ChromeType.GOOGLE).install())
  File "/Users/runtaowang/opt/anaconda3/lib/python3.9/site-packages/webdriver_manager/chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
  File "/Users/runtaowang/opt/anaconda3/lib/python3.9/site-packages/webdriver_manager/core/manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
  File "/Users/runtaowang/opt/anaconda3/lib/python3.9/site-packages/webdriver_manager/core/download_manager.py", line 28, in download_file
    response = self._http_client.get(url)
  File "/Users/runtaowang/opt/anaconda3/lib/python3.9/site-packages/webdriver_manager/core/http.py", line 33, in get
    self.validate_response(resp)
  File "/Users/runtaowang/opt/anaconda3/lib/python3.9/site-packages/webdriver_manager/core/http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/116.0.5845/chromedriver_mac64_m1.zip

**Comment by aimkiray** [comment]
Either Chrome or Chromium is fine. You can update to version 0.2.3 for more configuration options. See the README for details.
